### ISSUE TITLE
Sound loop bug

### ISSUE THREAD

**Issue by Dysse** [adngdb/llamazord#11]
Quand le son boucle il n'est plus arrêter lors du reset ce qui créer une superposition des musiques.

**Comment by Dysse** [comment]
j'ai trouvé la source du problème il faut que je remove l'event loop le problem c'est que je vois pas trop comment faire j'ai essayé plein de truc mais ça ne passe pas.

**Comment by adngdb** [comment]
De quel musique parles-tu ? Je ne peux pas reproduire ton problème de musique ni sur ma version locale, ni sur la version en ligne.
